# Generated by Django 5.1 on 2024-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cashondelivery', 'CashOnDelivery')], max_length=20),
        ),
    ]
